#include <fsl.h>

/* 64bit Size in Bytes */
typedef enum {
    a_BYTE_SZ       = 1,
    a_SHORT_SZ      = 2,
    a_INT_SZ        = 4,
    a_BOOL_SZ       = 4,
    a_FLOAT_SZ      = 4,
    a_DOUBLE_SZ     = 8,
    a_PTR_SZ        = 9
} type_sizes;

typedef enum {
    a_NULL          = -1,
	a_BYTE          = 1,
	a_SHORT         = 2,
	a_INT           = 3,
	a_BOOL          = 4,
	a_FLOAT         = 5,
	a_DOUBLE        = 6,
    a_VOID          = 7
} data_t;

#define DATA_T_COUNT 7

void *DATA_TYPES[][3] = {
	{(ptr)a_BYTE, 	    "byte",     (ptr)a_BYTE_SZ},
	{(ptr)a_SHORT,      "i16",      (ptr)a_SHORT_SZ},
	{(ptr)a_INT, 	    "i32",      (ptr)a_INT_SZ},
	{(ptr)a_BOOL, 	    "i32",      (ptr)a_BOOL_SZ},
	{(ptr)a_FLOAT, 	    "i64",      (ptr)a_FLOAT_SZ},
	{(ptr)a_DOUBLE,     "i64",      (ptr)a_DOUBLE_SZ},
	NULL
};

data_t find_type(string q)
{
	for(int i = 0; i < DATA_T_COUNT; i++)
	{
        int len = str_len((char *)((void **)DATA_TYPES[i])[1]);
		if(mem_cmp((char *)((void **)DATA_TYPES[i])[1], q, len))
        {
			return (data_t)DATA_TYPES[i][0];
        }
	}

	return false;
}

string find_stype(data_t q)
{
	for(int i = 0; i < DATA_T_COUNT; i++)
	{
		if(*(int *)DATA_TYPES[i][0] == q)
			return (string)DATA_TYPES[i][1];
	}

	return NULL;
}

struct parser_settings
{
	bool in_single_quote;
	bool in_double_quote;
	bool in_function;
	bool in_variable;
};

typedef struct {
    data_t  type;
    string  name;
    int     is_init;
    u8      *byteGen;       // Generated ByteCode
} var;

typedef struct
{
    data_t  type;
    string  name;
    int     parameters;
    u8      *byteGen;       // Generated ByteCode
} fnc;

var vars[25] = {0};
int var_count = 0;

fnc fncs[25] = {0};
int fnc_count = 0;

char *ERRORS[25] = {0};
int ERR_COUNT = 0;

bool validate_var(string line, int line_n)
{
    if(!line)
        return false;

    int argc = 0;
    sArr args = split_string(line, ' ', &argc);
    if(!argc || !args || argc < 2)
    {
        _sprintf(_OUTPUT_, "err: #%d, Invalid declaration, Missing variable name!", (void *[]){(ptr)&line_n});
        ERRORS[ERR_COUNT] = str_dup(_OUTPUT_);
        ERR_COUNT++;
        return false;
    }

    data_t type = find_type(args[0]);
    if(type == -1)
        return false;
        
    string name = str_dup(args[1]);

    var v;
    memzero(&v, sizeof(var));
    v.type = type;
    v.name = name;
    v.is_init = 0;

    printi(argc);
    if(argc == 2)
    {
        /* Declaration Detect Only */
        pfree_array((array)args);
        vars[var_count] = v;
        var_count++;
        
        return true;
    }

    /* Only accept '=' as operator upon initialization */
    if(argc > 2)
    {
        if(args[2][0] != '=')
        {
            _sprintf(_OUTPUT_, "err: #%d, Invalid variable initialization, Operator; '=' is the only operator accepted for initialization!", (void *[]){(ptr)&line_n});
            ERRORS[ERR_COUNT] = str_dup(_OUTPUT_);
            ERR_COUNT++;
            return false;
        }

        // ensure value is a actual type
        if(!is_number(args[3]) || !is_str_ascii(args[4]))
        {
            _sprintf(_OUTPUT_, "err: #%d, Invalid Variable RValue!", (void *[]){(ptr)&line_n});
            ERRORS[ERR_COUNT] = str_dup(_OUTPUT_);
            ERR_COUNT++;
            return false;
        }
    }

    v.is_init = true;
    // process value here.

    vars[var_count] = v;
    var_count++;

    pfree_array((array)args);
    return true;
}

/* Validate a function declaration */
bool validate_func(string line, int line_n)
{
    if(!line)
        return false;

    int argc = 0;
    sArr args = split_string(line, ' ', &argc);
    if(!argc || !args || argc < 2)
        return false;

    if(!is_str_ascii(args[1]))
    {
        _sprintf(_OUTPUT_, "err: #%d, Invalid declaration, Missing function name!", (void *[]){(ptr)&line_n});
        ERRORS[ERR_COUNT] = str_dup(_OUTPUT_);
        ERR_COUNT++;
        return false;
    }

    data_t type = find_type(args[0]);
    if(type == 0)
        return false;

    string name = str_dup(args[1]);

    // TODO; detect function parameters @ arg 3+
    // BUT WE'RE JUST GONNAH USE NO PARAMS FOR TESTING
    /* PARAMS MUST FOLLOW ABI ORDER */
    if(str_endswith(name, "()"))
    {
        // i8 entry() {}

        /* Parameters can be ignored if there isnt any */
        name[__get_size__(name) - 3] = '\0';
        name[__get_size__(name) - 2] = '\0';
    } else if(str_endswith(name, "(")) {
        // i8 entry( 
    } else if(argc >= 3 && str_startswith(args[3], "(")) {
        // i8 entry (string name) { }
    }

    /* Variable Detected */
    if(line[__get_size__(line) - 2] == ';')
        return false;

    /* Ensure params are after function name */
    int pos = find_string(line, args[1]);
    int opening = find_char(line, '(');
    /* Ensure the opening parathensis is not before the name lol */
    if(opening < pos)
    {
        _sprintf(_OUTPUT_, "err: #%d, Invalid function parameter declaration", (void *[]){(ptr)&line_n});
        ERRORS[ERR_COUNT] = str_dup(_OUTPUT_);
        ERR_COUNT++;
        return false;
    }

    int closing = find_char(line, ')');
    string arguments = get_sub_str(line, opening, closing);
    
    if(!mem_cmp(arguments, "()", 2))
    {
        arguments[__get_size__(arguments) - 2] = '\0';
        trim_char_idx(arguments, 0);

        println(arguments);
        int arg_c = 0;
        sArr arg_v = split_string(arguments, ',', &arg_c);

        if(arg_c)
        {
            for(int i = 0; i < arg_c; i++)
            {
                int param_argc = 0;
                sArr param_arg = split_string(arg_v[i], ' ', &param_argc);
                if(!param_argc || !param_arg)
                {
                    _sprintf(_OUTPUT_, "err: #%d, Invalid function parameter declaration!", (void *[]){(ptr)&line_n});
                    ERRORS[ERR_COUNT] = str_dup(_OUTPUT_);
                    ERR_COUNT++;
                    continue;
                }

                
                if(!find_type(param_arg[0]))
                {
                    _sprintf(_OUTPUT_, "err: #%d, Invalid function parameter declaration, Invalid type!", (void *[]){(ptr)&line_n});
                    ERRORS[ERR_COUNT] = str_dup(_OUTPUT_);
                    ERR_COUNT++;
                    continue;
                }

                if(param_argc > 0) pfree_array((array)param_arg);
            }

            pfree_array((array)arg_v);
        }
    }


    /* Validate Args */

    fnc fn;
    memzero(&fn, sizeof(fnc));
    fn.type = type;
    fn.name = name;

    mem_cpy(&fncs[fnc_count], &fn, sizeof(fn));
    fnc_count++;

    pfree_array((array)args);
    return true;
}

int entry(int argc, string argv[])
{
    int check = find_type("i8");
    _printf("Check: %d\n", &check);

	/* Simple NASM syntax Assembler */
	if(argc < 2)
	{
		_printf("Invalid arguments provided!\nUsage %s <file>\n", argv[0]);
		return 1;
	}

	fd_t fd = open_file(argv[1], 0, 0);
	if(!fd)
		fsl_panic("Unable to open file!");

	int sz 			= file_content_size(fd);
	string buffer 	= allocate(0, sz + 1);
	int bytes 		= file_read(fd, buffer, sz);
	if(bytes <= 0)
		fsl_panic("Read err");

	int line_count 	= 0;
	sArr lines 		= split_lines(buffer, &line_count);

	struct parser_settings s = {false};
	for(int i = 0; i < line_count; i++)
	{
		if(!lines[i])
			break;

		if(is_empty(lines[i])) continue;

        str_strip(lines[i]);
		int arg_c = 0;
		sArr args = split_string(lines[i], ' ', &arg_c);
		if(!arg_c || !args)
			continue;

		_printf("[%d]: %s\n", (ptr)&i, lines[i]);

        /* Function and Variable Detection (In-Function Variables Included) */
        int chk = find_type(args[0]);
		if(chk > -1)
		{
            /* In-Function Variable */
            if(s.in_function && lines[i][__get_size__(lines[i]) - 1] == ';')
            {
                // variable detected in function, must exit here
                // validate and append variable to fncs[i]->vars;
                continue;
            }

            /* Global Variable */
            if(lines[i][__get_size__(lines[i]) - 2] == ';')
            {
                // variable detected
                if(validate_var(lines[i], i))
                {
			        _printf("Variable found: %s\n", args[1]);
                    continue;
                }
            }

            if(!validate_func(lines[i], i))
                continue;

                
			_printf("Function found: %s\n", args[1]);
			s.in_function = true;
            continue;
		}

        /* In-Function Code Processing */
        if(s.in_function)
        {
            // Process Function Line and Generate to 
            if(str_cmp(lines[i], "}"))
            {
                s.in_function = false;
                continue;
            }
            continue;
        }

		pfree(args, 1);
		arg_c = 0;
	}

    if(ERR_COUNT > 0)
    {
        for(int i = 0; i < ERR_COUNT; i++)
            println(ERRORS[i]);
    }

    if(var_count > 0)
    {
        println("\x1b[32mListing Noted Variables:\x1b[39m");
        for(int i = 0; i < var_count; i++)
            _printf("Variable Noted: %s\n", vars[i].name);
    }

    if(fnc_count)
    {
        println("\x1b[32mListing Noted Functions:\x1b[39m");
        for(int i = 0; i < fnc_count; i++)
            _printf("Function Noted: %s\n", fncs[i].name);
    }

	return 0;
}